
import { Dataset, DataStory, StorySegment, ColumnType } from '../types';

export const generateLocalStory = (dataset: Dataset): DataStory => {
    // A simplified rule-based story generator (The "Local LLM" logic)
    // Runs instantly in browser without API calls
    
    const segments: StorySegment[] = [];
    const numCols = dataset.columns.filter(c => c.type === ColumnType.NUMBER);
    const catCols = dataset.columns.filter(c => c.type === ColumnType.STRING);
    
    // 1. Overview
    segments.push({
        id: 'seg_overview',
        title: 'Executive Summary',
        text: `Dataset contains ${dataset.rows.length} records analyzing ${dataset.columns.length} variables.`,
        audioScript: `Welcome to your data story. I've analyzed ${dataset.rows.length} records in this dataset. Let's dive into the key insights.`,
        chartId: undefined
    });

    // 2. Key Metrics Highlighting
    if (dataset.kpis.length > 0) {
        const primaryKPI = dataset.kpis[0];
        const trendText = primaryKPI.trend 
            ? `It is trending ${primaryKPI.trend > 0 ? 'up' : 'down'} by ${Math.abs(primaryKPI.trend)}%.` 
            : '';
        
        segments.push({
            id: 'seg_kpi',
            title: 'Primary Performance',
            text: `${primaryKPI.label}: ${primaryKPI.value}. ${trendText}`,
            audioScript: `The main headline is ${primaryKPI.label}, which currently sits at ${primaryKPI.value}. ${trendText}`,
            chartId: 'trend_main'
        });
    }

    // 3. Category Breakdown
    if (catCols.length > 0 && numCols.length > 0) {
        // Find top category
        const catCol = catCols[0].name;
        const numCol = numCols[0].name;
        
        // Simple aggregation
        const counts: Record<string, number> = {};
        dataset.rows.forEach(r => {
            const k = String(r[catCol]);
            const v = Number(r[numCol]) || 0;
            counts[k] = (counts[k] || 0) + v;
        });
        
        const sorted = Object.entries(counts).sort((a,b) => b[1] - a[1]);
        const top = sorted[0];
        
        if (top) {
            segments.push({
                id: 'seg_cat',
                title: 'Market Leader',
                text: `${top[0]} leads with ${top[1].toLocaleString()} in ${numCol}.`,
                audioScript: `When we break things down by ${catCol}, ${top[0]} is the clear leader, generating ${top[1].toLocaleString()} in ${numCol}.`,
                chartId: 'cat_breakdown'
            });
        }
    }

    // 4. Anomaly / Outlier (Mock detection)
    if (numCols.length > 0) {
        // Simple Z-score like check
        const values = dataset.rows.map(r => Number(r[numCols[0].name]) || 0);
        const max = Math.max(...values);
        
        segments.push({
            id: 'seg_outlier',
            title: 'Peak Performance',
            text: `Peak value detected: ${max.toLocaleString()}.`,
            audioScript: `I also noticed a significant peak in the data, reaching a high of ${max.toLocaleString()}. This outlier might be worth investigating further.`,
            chartId: 'boxplot_distribution'
        });
    }

    // 5. Conclusion
    segments.push({
        id: 'seg_conc',
        title: 'Recommendation',
        text: 'Focus on top performing segments to maximize growth.',
        audioScript: 'Based on this, I recommend focusing resources on the top performing segments we identified to sustain this momentum. That concludes the report.',
        chartId: undefined
    });

    return {
        title: `Deep Dive: ${dataset.name}`,
        summary: 'Automated insights generated by InsightX Local Engine.',
        segments
    };
};
